/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package printer;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Mostafa
 */
public class adminOperations extends javax.swing.JFrame {
    loginORSign loginOrSignUp=new loginORSign();
    private static int ID;
    private static  String Password;

    public adminOperations() {
        initComponents();
    }

    public adminOperations(int ID, String password) {
        this();
        this.ID = ID;
        this.Password = password;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setCredit = new javax.swing.JButton();
        getCredit = new javax.swing.JButton();
        setEmail = new javax.swing.JButton();
        makeRequest = new javax.swing.JButton();
        getDocument = new javax.swing.JButton();
        uploadDocument = new javax.swing.JButton();
        getMoney = new javax.swing.JButton();
        getRequestInfo = new javax.swing.JButton();
        getRequestState = new javax.swing.JButton();
        printDocument = new javax.swing.JButton();
        setMoney = new javax.swing.JButton();
        logOut = new javax.swing.JButton();
        getEmail = new javax.swing.JButton();
        setName = new javax.swing.JButton();
        deleteUser = new javax.swing.JButton();
        getName = new javax.swing.JButton();
        searchUser = new javax.swing.JButton();
        printAll = new javax.swing.JButton();
        updatePassword = new javax.swing.JButton();
        assignTask = new javax.swing.JButton();
        addUser = new javax.swing.JButton();
        setId = new javax.swing.JButton();
        disapprovePrintingRequest = new javax.swing.JButton();
        approvePrintingRequest = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        setCredit.setText("setCredit");
        setCredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setCreditActionPerformed(evt);
            }
        });

        getCredit.setText("getCredit");
        getCredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getCreditActionPerformed(evt);
            }
        });

        setEmail.setText("setEmail");
        setEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setEmailActionPerformed(evt);
            }
        });

        makeRequest.setText("makeRequest");
        makeRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeRequestActionPerformed(evt);
            }
        });

        getDocument.setText("getDocument");
        getDocument.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getDocumentActionPerformed(evt);
            }
        });

        uploadDocument.setText("uploadDoc");
        uploadDocument.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadDocumentActionPerformed(evt);
            }
        });

        getMoney.setText("getMoney");
        getMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getMoneyActionPerformed(evt);
            }
        });

        getRequestInfo.setText("getRequestInfo");
        getRequestInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getRequestInfoActionPerformed(evt);
            }
        });

        getRequestState.setText("getRequestState");
        getRequestState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getRequestStateActionPerformed(evt);
            }
        });

        printDocument.setText("printDocument");
        printDocument.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printDocumentActionPerformed(evt);
            }
        });

        setMoney.setText("setMoney");
        setMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setMoneyActionPerformed(evt);
            }
        });

        logOut.setText("LOG OUT");
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });

        getEmail.setText("getEmail");
        getEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getEmailActionPerformed(evt);
            }
        });

        setName.setText("setName");
        setName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setNameActionPerformed(evt);
            }
        });

        deleteUser.setText("deleteUser");
        deleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteUserActionPerformed(evt);
            }
        });

        getName.setText("getName");
        getName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getNameActionPerformed(evt);
            }
        });

        searchUser.setText("searchUser");
        searchUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchUserActionPerformed(evt);
            }
        });

        printAll.setText("printAll");
        printAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printAllActionPerformed(evt);
            }
        });

        updatePassword.setText("updatePassword");
        updatePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePasswordActionPerformed(evt);
            }
        });

        assignTask.setText("assignTask");
        assignTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignTaskActionPerformed(evt);
            }
        });

        addUser.setText("addUser");
        addUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserActionPerformed(evt);
            }
        });

        setId.setText("setId");
        setId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setIdActionPerformed(evt);
            }
        });

        disapprovePrintingRequest.setText("disapprovePrintingRequest");
        disapprovePrintingRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disapprovePrintingRequestActionPerformed(evt);
            }
        });

        approvePrintingRequest.setText("approvePrintingRequest");
        approvePrintingRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approvePrintingRequestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(20, 20, 20)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(getDocument, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(getRequestInfo, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(printDocument)
                                            .addGap(66, 66, 66)
                                            .addComponent(setMoney))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(setName)
                                            .addComponent(getCredit))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(printAll)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(getRequestState)
                                            .addComponent(uploadDocument)
                                            .addComponent(setEmail)
                                            .addComponent(getName)))))
                            .addComponent(logOut, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(getMoney)
                            .addComponent(makeRequest)
                            .addComponent(setCredit)
                            .addComponent(getEmail)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(updatePassword)
                                .addGap(40, 40, 40)
                                .addComponent(assignTask))
                            .addComponent(searchUser)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(approvePrintingRequest)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(disapprovePrintingRequest)
                                .addGap(51, 51, 51)
                                .addComponent(setId)))
                        .addGap(20, 20, 20)))
                .addGap(27, 27, 27))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(addUser)
                .addGap(60, 60, 60)
                .addComponent(deleteUser)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(logOut))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deleteUser)
                            .addComponent(addUser)
                            .addComponent(searchUser))))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assignTask)
                    .addComponent(updatePassword)
                    .addComponent(printAll))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(setId)
                    .addComponent(disapprovePrintingRequest)
                    .addComponent(approvePrintingRequest))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(getEmail)
                    .addComponent(setName)
                    .addComponent(getName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(setCredit)
                    .addComponent(getCredit)
                    .addComponent(setEmail))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(makeRequest)
                    .addComponent(getDocument)
                    .addComponent(uploadDocument))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(getMoney)
                    .addComponent(getRequestInfo)
                    .addComponent(getRequestState))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(printDocument)
                    .addComponent(setMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uploadDocumentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadDocumentActionPerformed
        uploadDocument set=new uploadDocument(ID,Password);
        set.show();
        set.setLocation(400, 300);
        set.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_uploadDocumentActionPerformed

    private void setMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setMoneyActionPerformed
        setMoney set=new setMoney();
        set.show();
        set.setLocation(400, 300);
        set.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_setMoneyActionPerformed

    private void setEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setEmailActionPerformed
        setEmail set=new setEmail(ID,Password);
        set.show();
        set.setLocation(400, 300);
        set.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_setEmailActionPerformed

    private void getDocumentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getDocumentActionPerformed
        getDocument set=new getDocument(ID,Password);
        set.show();
        set.setLocation(400, 300);
        set.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_getDocumentActionPerformed

    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutActionPerformed
        this.dispose();
        loginOrSignUp.setVisible(true);
    }//GEN-LAST:event_logOutActionPerformed

    private void setCreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setCreditActionPerformed
        setCredit set=new setCredit(ID,Password);
        set.show();
        set.setLocation(400, 300);
        set.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_setCreditActionPerformed

    private void getCreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getCreditActionPerformed
        getcredit set=new getcredit(ID,Password);
        set.show();
        set.setLocation(400, 300);
        set.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_getCreditActionPerformed

    private void makeRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeRequestActionPerformed
        makeRequest set=new makeRequest(ID,Password);
        set.show();
        set.setLocation(400, 300);
        set.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_makeRequestActionPerformed

    private void getMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getMoneyActionPerformed
        getMoney set=new getMoney(ID,Password);
        set.show();
        set.setLocation(400, 300);
        set.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_getMoneyActionPerformed

    private void getRequestInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getRequestInfoActionPerformed
        requestInfo set=new requestInfo(ID,Password);
        set.show();
        set.setLocation(600, 400);
        set.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_getRequestInfoActionPerformed

    private void getRequestStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getRequestStateActionPerformed
        status set=new status(ID,Password);
        set.show();
        set.setLocation(400, 300);
        set.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_getRequestStateActionPerformed

    private void printDocumentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printDocumentActionPerformed
        printDocument set=new printDocument(ID,Password);
        set.show();
        set.setLocation(400, 300);
        set.setSize(600, 400);
        set.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_printDocumentActionPerformed

    private void getEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getEmailActionPerformed
        getEmail set=new getEmail(ID,Password);
        set.show();
        set.setLocation(400, 300);
        set.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_getEmailActionPerformed

    private void setNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setNameActionPerformed
        setName set=new setName(ID,Password);
        set.show();
        set.setLocation(400, 300);
        set.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_setNameActionPerformed

    private void deleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteUserActionPerformed
        deleteUser set=new deleteUser();
        set.show();
        set.setLocation(400, 300);
        set.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_deleteUserActionPerformed

    private void getNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getNameActionPerformed
        getName set=new getName(ID,Password);
        set.show();
        set.setLocation(400, 300);
        set.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_getNameActionPerformed

    private void searchUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchUserActionPerformed
        searchUser set=new searchUser();
        set.show();
        set.setLocation(400, 300);
         set.setSize(600, 400);
        set.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_searchUserActionPerformed

    private void printAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printAllActionPerformed
        try {
            printAllUsers set=new printAllUsers();
            set.show();
            set.setLocation(400, 300);
            set.setSize(1000, 500);
            set.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(adminOperations.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_printAllActionPerformed

    private void updatePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePasswordActionPerformed
        updatePassword set=new updatePassword(ID,Password);
        set.show();
        set.setLocation(400, 300);
        set.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_updatePasswordActionPerformed

    private void assignTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignTaskActionPerformed
        assignTask set=new assignTask();
        set.show();
        set.setLocation(400, 300);
        set.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_assignTaskActionPerformed

    private void addUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserActionPerformed
        addUser set=new addUser();
        set.show();
        set.setLocation(400, 300);
        set.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addUserActionPerformed

    private void setIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setIdActionPerformed
        setId set=new setId(ID,Password);
        set.show();
        set.setLocation(400, 300);
        set.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_setIdActionPerformed

    private void disapprovePrintingRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disapprovePrintingRequestActionPerformed
        disApprove set=new disApprove();
        set.show();
        set.setLocation(400, 300);
        set.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_disapprovePrintingRequestActionPerformed

    private void approvePrintingRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approvePrintingRequestActionPerformed
        approve set=new approve();
        set.show();
        set.setLocation(400, 300);
        set.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_approvePrintingRequestActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminOperations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminOperations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminOperations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminOperations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addUser;
    private javax.swing.JButton approvePrintingRequest;
    private javax.swing.JButton assignTask;
    private javax.swing.JButton deleteUser;
    private javax.swing.JButton disapprovePrintingRequest;
    private javax.swing.JButton getCredit;
    private javax.swing.JButton getDocument;
    private javax.swing.JButton getEmail;
    private javax.swing.JButton getMoney;
    private javax.swing.JButton getName;
    private javax.swing.JButton getRequestInfo;
    private javax.swing.JButton getRequestState;
    private javax.swing.JButton logOut;
    private javax.swing.JButton makeRequest;
    private javax.swing.JButton printAll;
    private javax.swing.JButton printDocument;
    private javax.swing.JButton searchUser;
    private javax.swing.JButton setCredit;
    private javax.swing.JButton setEmail;
    private javax.swing.JButton setId;
    private javax.swing.JButton setMoney;
    private javax.swing.JButton setName;
    private javax.swing.JButton updatePassword;
    private javax.swing.JButton uploadDocument;
    // End of variables declaration//GEN-END:variables

}
