/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package printer;

/**
 *
 * @author Mostafa
 */
public class userOperation extends javax.swing.JFrame {
    private static int ID;
    private static String Password;
    loginORSign loginOrSignUp = new loginORSign();

    public userOperation() {
        initComponents();
    }
        public userOperation(int ID,String password) {
        this();
        this.ID = ID;
        this.Password = password;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        getMoney = new javax.swing.JButton();
        printDocument = new javax.swing.JButton();
        requestInfo = new javax.swing.JButton();
        setId = new javax.swing.JButton();
        getName = new javax.swing.JButton();
        setName = new javax.swing.JButton();
        getEmail = new javax.swing.JButton();
        setEmail = new javax.swing.JButton();
        uploadDocument = new javax.swing.JButton();
        setCredit = new javax.swing.JButton();
        logOut = new javax.swing.JButton();
        getcredit = new javax.swing.JButton();
        status = new javax.swing.JButton();
        makeRequest = new javax.swing.JButton();
        getDocument = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        getMoney.setText("get my money");
        getMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getMoneyActionPerformed(evt);
            }
        });

        printDocument.setText("print my document");
        printDocument.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printDocumentActionPerformed(evt);
            }
        });

        requestInfo.setText("information of my request");
        requestInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestInfoActionPerformed(evt);
            }
        });

        setId.setText("set Id");
        setId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setIdActionPerformed(evt);
            }
        });

        getName.setText("get Name");
        getName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getNameActionPerformed(evt);
            }
        });

        setName.setText("set Name");
        setName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setNameActionPerformed(evt);
            }
        });

        getEmail.setText("get Email");
        getEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getEmailActionPerformed(evt);
            }
        });

        setEmail.setText("set Email");
        setEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setEmailActionPerformed(evt);
            }
        });

        uploadDocument.setText("upload document");
        uploadDocument.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadDocumentActionPerformed(evt);
            }
        });

        setCredit.setText("set credit");
        setCredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setCreditActionPerformed(evt);
            }
        });

        logOut.setText("LOG OUT");
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });

        getcredit.setText("get credit");
        getcredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getcreditActionPerformed(evt);
            }
        });

        status.setText("status of my request");
        status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusActionPerformed(evt);
            }
        });

        makeRequest.setText("make request");
        makeRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeRequestActionPerformed(evt);
            }
        });

        getDocument.setText("get document");
        getDocument.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getDocumentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(setName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 221, Short.MAX_VALUE)
                .addComponent(getName)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(logOut, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(requestInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(printDocument)
                .addGap(18, 18, 18)
                .addComponent(getMoney))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(setId)
                            .addGap(95, 95, 95))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(getEmail)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(getDocument)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(getcredit)
                                                .addGap(62, 62, 62)
                                                .addComponent(setCredit)))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(173, 173, 173)
                                    .addComponent(makeRequest)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(status)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(setEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(uploadDocument, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(logOut)
                .addGap(39, 39, 39)
                .addComponent(getName)
                .addGap(18, 18, 18)
                .addComponent(setName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(getMoney)
                    .addComponent(printDocument)
                    .addComponent(requestInfo))
                .addGap(29, 29, 29))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(155, 155, 155)
                            .addComponent(getcredit))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(62, 62, 62)
                            .addComponent(setId)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(getEmail)
                                .addComponent(setEmail))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(uploadDocument)
                                .addComponent(setCredit))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(17, 17, 17)
                            .addComponent(status))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(makeRequest)
                                .addComponent(getDocument))))
                    .addContainerGap(72, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutActionPerformed
        this.dispose();
        loginOrSignUp.setVisible(true);
    }//GEN-LAST:event_logOutActionPerformed

    private void makeRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeRequestActionPerformed
        makeRequest set=new makeRequest(ID,Password);
        set.show();
        set.setLocation(400, 300);
        set.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_makeRequestActionPerformed

    private void setIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setIdActionPerformed
        setId set=new setId(ID,Password);
        set.show();
        set.setLocation(400, 300);
        set.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_setIdActionPerformed

    private void getNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getNameActionPerformed
        getName set=new getName(ID,Password);
        set.show();
        set.setLocation(400, 300);
        set.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_getNameActionPerformed

    private void setNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setNameActionPerformed
        setName set=new setName(ID,Password);
        set.show();
        set.setLocation(400, 300);
        set.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_setNameActionPerformed

    private void getEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getEmailActionPerformed
        getEmail set=new getEmail(ID,Password);
        set.show();
        set.setLocation(400, 300);
        set.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_getEmailActionPerformed

    private void setEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setEmailActionPerformed
        setEmail set=new setEmail(ID,Password);
        set.show();
        set.setLocation(400, 300);
        set.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_setEmailActionPerformed

    private void uploadDocumentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadDocumentActionPerformed
        uploadDocument set=new uploadDocument(ID,Password);
        set.show();
        set.setLocation(400, 300);
        set.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_uploadDocumentActionPerformed

    private void setCreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setCreditActionPerformed
        setCredit set=new setCredit(ID,Password);
        set.show();
        set.setLocation(400, 300);
        set.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_setCreditActionPerformed

    private void getcreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getcreditActionPerformed
        getcredit set=new getcredit(ID,Password);
        set.show();
        set.setLocation(400, 300);
        set.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_getcreditActionPerformed

    private void getDocumentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getDocumentActionPerformed
        getDocument set=new getDocument(ID,Password);
        set.show();
        set.setLocation(400, 300);
         set.setSize(600, 400);
        set.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_getDocumentActionPerformed

    private void statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusActionPerformed
        status set=new status(ID,Password);
        set.show();
        set.setLocation(400, 300);
        set.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_statusActionPerformed

    private void getMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getMoneyActionPerformed
        getMoney set=new getMoney(ID,Password);
        set.show();
        set.setLocation(400, 300);
        set.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_getMoneyActionPerformed

    private void printDocumentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printDocumentActionPerformed
        printDocument set=new printDocument(ID,Password);
        set.show();
        set.setLocation(400, 300);
         set.setSize(600, 400);
        set.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_printDocumentActionPerformed

    private void requestInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestInfoActionPerformed
       requestInfo set=new requestInfo(ID,Password);
        set.show();
        set.setLocation(400, 300);
         set.setSize(600, 400);
        set.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_requestInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userOperation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userOperation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userOperation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userOperation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton getDocument;
    private javax.swing.JButton getEmail;
    private javax.swing.JButton getMoney;
    private javax.swing.JButton getName;
    private javax.swing.JButton getcredit;
    private javax.swing.JButton logOut;
    private javax.swing.JButton makeRequest;
    private javax.swing.JButton printDocument;
    private javax.swing.JButton requestInfo;
    private javax.swing.JButton setCredit;
    private javax.swing.JButton setEmail;
    private javax.swing.JButton setId;
    private javax.swing.JButton setName;
    private javax.swing.JButton status;
    private javax.swing.JButton uploadDocument;
    // End of variables declaration//GEN-END:variables
}
